"""Export Test-Agent metrics as APM dashboard JSON (Datadog / Grafana compatible)."""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from runtime.observability.dashboard import build_dashboard
from runtime.config.settings import get_settings

logger = logging.getLogger(__name__)


def export_datadog_dashboard(
    output: str | Path,
    title: str = "Test-Agent Quality",
    workspace_dir: Optional[Path] = None,
) -> Path:
    """Generate a Datadog dashboard JSON with test quality widgets."""
    ws = workspace_dir or get_settings().workspace_dir
    data = build_dashboard(ws)
    decision = data.get("decision", {})
    diagnostic = data.get("diagnostic", {})

    dashboard: Dict[str, Any] = {
        "title": title,
        "description": "Auto‑generated by Test-Agent",
        "layout_type": "ordered",
        "widgets": [
            {
                "definition": {
                    "type": "query_value",
                    "title": "Pass Rate",
                    "requests": [{"q": f"avg:test.pass_rate{{{decision.get('pass_rate_pct', 0)}}}", "aggregator": "avg"}],
                }
            },
            {
                "definition": {
                    "type": "query_value",
                    "title": "MTTD (min)",
                    "requests": [{"q": f"avg:test.mttd_minutes{{{decision.get('mttd_minutes', 0)}}}", "aggregator": "avg"}],
                }
            },
            {
                "definition": {
                    "type": "query_value",
                    "title": "MTTR (min)",
                    "requests": [{"q": f"avg:test.mttr_minutes{{{decision.get('mttr_minutes', 0)}}}", "aggregator": "avg"}],
                }
            },
            {
                "definition": {
                    "type": "query_table",
                    "title": "Expert Health",
                    "requests": [{"q": "top(test.expert_fails, 10, 'avg', 'desc')"}],
                }
            },
            {
                "definition": {
                    "type": "query_value",
                    "title": "Flaky Candidates",
                    "requests": [{"q": f"avg:test.flaky_candidates{{{len(diagnostic.get('flaky_candidates', []))}}}", "aggregator": "avg"}],
                }
            },
        ],
        "template_variables": [
            {"name": "env", "default": "*", "prefix": "env"},
        ],
    }

    out = Path(output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(dashboard, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.info(f"Datadog dashboard exported: {out}")
    return out


def export_grafana_dashboard(
    output: str | Path,
    title: str = "Test-Agent Quality",
    workspace_dir: Optional[Path] = None,
) -> Path:
    """Generate a Grafana dashboard JSON with test quality panels."""
    ws = workspace_dir or get_settings().workspace_dir
    data = build_dashboard(ws)
    decision = data.get("decision", {})
    diagnostic = data.get("diagnostic", {})

    now = datetime.now(timezone.utc).isoformat()

    dashboard = {
        "dashboard": {
            "title": title,
            "tags": ["test-agent", "quality"],
            "timezone": "browser",
            "panels": [
                {
                    "title": "Pass Rate",
                    "type": "stat",
                    "gridPos": {"h": 4, "w": 6, "x": 0, "y": 0},
                    "targets": [{"expr": f"test_pass_rate{{app=\"tagent\"}}", "legendFormat": "pass"}],
                    "fieldConfig": {"defaults": {"thresholds": {"steps": [{"value": None, "color": "red"}, {"value": 60, "color": "yellow"}, {"value": 85, "color": "green"}]}}},
                },
                {
                    "title": "Trend",
                    "type": "stat",
                    "gridPos": {"h": 4, "w": 6, "x": 6, "y": 0},
                    "targets": [{"expr": f"test_trend{{app=\"tagent\"}}", "legendFormat": decision.get("trend", "stable")}],
                },
                {
                    "title": "Expert Failures (Top 10)",
                    "type": "table",
                    "gridPos": {"h": 8, "w": 12, "x": 0, "y": 4},
                    "targets": [{"expr": "topk(10, test_expert_fails{app=\"tagent\"})", "format": "table"}],
                },
                {
                    "title": "Flaky Candidates",
                    "type": "table",
                    "gridPos": {"h": 6, "w": 12, "x": 0, "y": 12},
                    "targets": [{"expr": f"test_flaky_candidates{{app=\"tagent\"}}", "format": "table"}],
                },
            ],
            "time": {"from": "now-7d", "to": "now"},
        },
        "overwrite": True,
    }

    out = Path(output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(dashboard, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.info(f"Grafana dashboard exported: {out}")
    return out
