# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Test-Agent backend as a standalone executable."""

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(os.getcwd())
RUNTIME = PROJECT_ROOT / "runtime"

a = Analysis(
    [str(PROJECT_ROOT / "desktop" / "entrypoint.py")],
    pathex=[str(PROJECT_ROOT), str(RUNTIME)],
    binaries=[],
    datas=[
        (str(PROJECT_ROOT / "agents"), "agents"),
        (str(PROJECT_ROOT / "skills"), "skills"),
        (str(PROJECT_ROOT / "config"), "config"),
        (str(PROJECT_ROOT / "utils"), "utils"),
        (str(PROJECT_ROOT / "VERSION"), "."),
    ],
    hiddenimports=[
        "runtime.api.main",
        "runtime.api.deps",
        "runtime.api.models",
        "runtime.api.parsers",
        "runtime.cli.main",
        "runtime.cli.config",
        "runtime.config.settings",
        "runtime.config.safety",
        "runtime.orchestrator.direct",
        "runtime.orchestrator.adapters.experts",
        "runtime.orchestrator.adapters.scripts",
        "runtime.orchestrator.agents",
        "runtime.orchestrator.skills",
        "runtime.router.router",
        "runtime.router.llm_client",
        "runtime.router.schema",
        "runtime.registry.registry",
        "runtime.storage.repo",
        "runtime.storage.db",
        "runtime.storage.models",
        "runtime.tutor.i18n",
        "runtime.tutor.verbosity",
        "runtime.healthcheck.agent_smoke",
        "runtime.exporters.base",
        "runtime.exporters.xmind",
        "runtime.exporters.markmap",
        "runtime.exporters.opml",
        "runtime.observability.logging",
        "runtime.init.matrix",
        "runtime.init.renderer",
        "runtime.init.wizard",
        "runtime.mcp",
        "runtime.mcp.base",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan.on",
        "fastapi",
        "pydantic",
        "pydantic_settings",
        "loguru",
        "prefect",
        "sqlalchemy",
        "psycopg",
        "pgvector",
        "minio",
        "litellm",
        "httpx",
        "pyyaml",
        "pypdf",
        "python_docx",
        "rich",
        "openpyxl",
        "factory",
        "faker",
        "tenacity",
        "requests",
        "bs4",
        "pdfplumber",
        "websocket",
        "python_multipart",
        "typer",
        "mcp",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="tagent-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
