"""`tagent bootstrap` — one‑command install: check → configure → verify."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import typer
from rich.panel import Panel

from runtime.cli._shared import console


def _check_python() -> tuple[bool, str]:
    v = sys.version_info
    ok = v >= (3, 10)
    detail = f"{v.major}.{v.minor}.{v.micro}"
    return ok, detail


def _check_git() -> tuple[bool, str]:
    git = shutil.which("git")
    if not git:
        return False, "not found"
    try:
        r = subprocess.run([git, "--version"], capture_output=True, text=True, timeout=10)
        return True, r.stdout.strip().split()[-1] if r.returncode == 0 else "error"
    except Exception:
        return False, "error"


def _check_pip() -> tuple[bool, str]:
    try:
        import pip
        return True, pip.__version__
    except ImportError:
        return False, "not found"


def _check_llm_env() -> tuple[bool, str]:
    provider = os.getenv("TAGENT_LLM_PROVIDER", "")
    key = os.getenv("TAGENT_LLM_API_KEY", "")
    if not provider and not key:
        alt = os.getenv("OPENAI_API_KEY", "") or os.getenv("ANTHROPIC_API_KEY", "") or os.getenv("DASHSCOPE_API_KEY", "")
        if alt:
            return True, "LLM key found (generic)"
        return False, "no LLM provider configured — set TAGENT_LLM_PROVIDER + TAGENT_LLM_API_KEY in .env"
    if not key:
        return False, f"provider={provider} but no API key — set TAGENT_LLM_API_KEY"
    return True, f"provider={provider}"


_ENV_TEMPLATE = """\
# Test-Agent minimal config (generated by `tagent bootstrap`)
TAGENT_LLM_PROVIDER=deepseek
TAGENT_LLM_API_KEY=sk-your-key-here
TAGENT_LLM_MODEL=deepseek-chat
TAGENT_LOG_LEVEL=INFO
"""


def _write_minimal_env(target: Path, force: bool = False) -> None:
    if target.exists() and not force:
        return
    target.write_text(_ENV_TEMPLATE.lstrip(), encoding="utf-8")


def _check_env_file() -> tuple[bool, str]:
    for p in [Path(".env"), Path("runtime/.env")]:
        if p.exists():
            return True, str(p)
    return False, "not found"


def register(app: typer.Typer) -> None:

    @app.command()
    def bootstrap(
        force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing .env"),
    ) -> None:
        """One‑command bootstrap: check system → generate config → verify setup."""
        console.print("[bold]Test-Agent Bootstrap[/]\n")

        all_ok = True

        # ── 1. System checks ──
        console.print("[bold]1. System checks[/]")
        for name, check in [("Python 3.10+", _check_python), ("Git", _check_git), ("pip", _check_pip)]:
            ok, detail = check()
            icon = "[green]✓[/]" if ok else "[red]✗[/]"
            console.print(f"  {icon} {name}: {detail}")
            if not ok:
                all_ok = False

        if not all_ok:
            console.print("\n[red]Fix system requirements above, then re‑run `tagent bootstrap`.[/]")
            raise typer.Exit(code=1)

        # ── 2. Config generation ──
        console.print("\n[bold]2. Config[/]")
        env_ok, env_path = _check_env_file()
        if env_ok and not force:
            console.print(f"  [green]✓[/] .env exists at {env_path} (use --force to overwrite)")
        else:
            try:
                _write_minimal_env(Path(".env"), force=force)
                console.print("  [green]✓[/] generated .env (minimal template)")
            except Exception as e:
                console.print(f"  [yellow]![/] .env generation skipped: {e}")

        # ── 3. LLM config check ──
        console.print("\n[bold]3. LLM[/]")
        llm_ok, llm_detail = _check_llm_env()
        if llm_ok:
            console.print(f"  [green]✓[/] {llm_detail}")
        else:
            console.print(f"  [yellow]![/] {llm_detail}")
            console.print("  [dim]Edit .env and set TAGENT_LLM_PROVIDER + TAGENT_LLM_API_KEY.[/]")

        # ── 4. Verify ──
        console.print("\n[bold]4. Verify[/]")
        try:
            ver = sys.version_info
            console.print(f"  [green]✓[/] Python {ver.major}.{ver.minor}.{ver.micro}")
            import runtime
            console.print(f"  [green]✓[/] Test-Agent Runtime v{runtime.__version__}")
        except ImportError as e:
            console.print(f"  [red]✗[/] import failed: {e}")
            all_ok = False

        # ── Ready ──
        console.print()
        if all_ok:
            console.print(Panel.fit(
                "[bold green]Bootstrap complete![/]\n\n"
                "Next steps:\n"
                "  1. Edit .env → set your LLM API key\n"
                "  2. Run [bold]tagent demo -y[/] to verify\n"
                "  3. Run [bold]tagent run --prd your-prd.md[/] with your own project",
                title="Ready",
                border_style="green",
            ))
        else:
            console.print(Panel.fit(
                "[bold yellow]Bootstrap partial — some checks failed.[/]\n"
                "Fix issues above and re‑run [bold]tagent bootstrap[/]",
                title="Action Required",
                border_style="yellow",
            ))
            raise typer.Exit(code=1)
